[settings]
experimental = true # To enable installation of Go tools from source with mise.

[tools]
actionlint = "1.7.9"
buf = "1.60.0"
container-structure-test = "1.22.0"
ginkgo = "2.27.2"
go = "1.25.4"
hadolint = "2.14.0"
helm = "4.0.1"
helm-docs = "1.14.2"
kind = "0.30.0"
kubectl = "1.34.2"
protoc = "33.1"
shellcheck = "0.11.0"
yq = "4.48.2"
node = "20"
"npm:@redocly/cli" = "latest"
"npm:oas-toolkit" = "latest"
"aqua:bufbuild/protoc-gen-validate" = "1.2.1"
"aqua:grpc/grpc-go/protoc-gen-go-grpc" = "1.6.0"
"aqua:helm/chart-releaser" = "1.8.1"
"aqua:k3d-io/k3d" = "5.8.3"
"aqua:protocolbuffers/protobuf-go/protoc-gen-go" = "1.36.10"
"aqua:stackrox/kube-linter" = "0.7.6"
"go:github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema" = "v0.0.0-20230606235304-e35f2ad05c0c"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "v2.5.1"
"go:sigs.k8s.io/controller-tools/cmd/controller-gen" = "v0.19.0"
"go:sigs.k8s.io/controller-runtime/tools/setup-envtest" = "v0.0.0-20251126220622-4b46eb04d57f"
# === tools excluded from GitHub Actions installs ===
# ⚠️ If you change any tool name below, update `MISE_DISABLE_TOOLS` in:
#     .github/workflows/_build_publish.yaml
#     .github/workflows/_e2e.yaml
#     .github/workflows/_test.yaml
#     .github/workflows/build-test-distribute.yaml
#     .github/workflows/merge-release-to-master.yaml
#     .github/workflows/pr-comments.yaml
#     .github/workflows/transparentproxy-tests.yaml
#     .github/workflows/update-insecure-dependencies.yaml
golangci-lint = "2.6.2"
skaffold = "2.17.0"
