[settings]
experimental = true # To enable installation of Go tools from source with mise.

[tools]
container-structure-test = "1.19.3"
ginkgo = "2.23.4"
hadolint = "2.12.1-beta"
helm = "3.18.4"
helm-docs = "1.11.0"
kind = "0.24.0"
kubectl = "1.32.6"
protoc = "3.20.0"
shellcheck = "0.10.0"
yq = "4.47.1"
"aqua:bufbuild/protoc-gen-validate" = "1.2.1"
"aqua:grpc/grpc-go/protoc-gen-go-grpc" = "1.5.1"
"aqua:helm/chart-releaser" = "1.7.0"
"aqua:k3d-io/k3d" = "5.8.3"
"aqua:protocolbuffers/protobuf-go/protoc-gen-go" = "1.28.1"
"aqua:stackrox/kube-linter" = "0.7.1"
"go:github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema" = "v0.0.0-20230606235304-e35f2ad05c0c"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "v2.4.1"
"go:sigs.k8s.io/controller-tools/cmd/controller-gen" = "v0.18.0"
"go:sigs.k8s.io/controller-runtime/tools/setup-envtest" = "v0.0.0-20250731065915-e8c5c5445a20"
# === tools excluded from GitHub Actions installs ===
# ⚠️ If you change any tool name below, update `MISE_DISABLE_TOOLS` in:
#     .github/workflows/_build_publish.yaml
#     .github/workflows/_e2e.yaml
#     .github/workflows/_test.yaml
#     .github/workflows/build-test-distribute.yaml
#     .github/workflows/merge-release-to-master.yaml
#     .github/workflows/pr-comments.yaml
#     .github/workflows/transparentproxy-tests.yaml
#     .github/workflows/update-insecure-dependencies.yaml
clang-format = "13.0.0"
golangci-lint = "2.3.1"
skaffold = "2.16.1"
