{{ range $secret := $.Values.controlPlane.additionalK8sSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $secret.name $ | quote }}
  labels:
    {{- include "kuma.labels" $ | nindent 4 }}
    app: {{ include "kuma.name" $ }}-control-plane
    {{ range $key, $value := $.Values.controlPlane.extraLabels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{ end }}
stringData:
  {{ range $key, $value := $secret.stringData }}
  {{ $key | quote }}: {{ $value | quote }}
  {{ end }}
{{ end }}
