{{- if .Values.ingress.enabled }}
{{- if or (eq .Values.controlPlane.mode "global") (eq .Values.controlPlane.mode "standalone") }}
{{ fail "You shouldn't run zoneIngress when running the CP in global or standalone" }}
{{- end }}
{{- end }}
{{- if and .Values.ingress.enabled .Values.ingress.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuma.ingress.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kuma.ingressLabels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.ingress.service.type }}
  {{- if .Values.ingress.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.ingress.service.loadBalancerIP | toYaml }}
  {{- end }}
  {{- if .Values.ingress.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
  {{- range .Values.ingress.service.loadBalancerSourceRanges }}
    - {{.}}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.ingress.service.port }}
      protocol: TCP
      targetPort: 10001
    {{- if and (eq .Values.ingress.service.type "NodePort")  .Values.ingress.service.nodePort }}
      nodePort: {{ .Values.ingress.service.nodePort }}
    {{- end }}
  selector:
    app: {{ include "kuma.name" . }}-ingress
  {{- include "kuma.selectorLabels" . | nindent 4 }}
{{- end }}
