{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuma.ingress.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "kuma.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ingress.service.type }}
  ports:
    - port: 10001
      protocol: TCP
      targetPort: 10001
  selector:
    app: kuma-ingress
  {{- include "kuma.selectorLabels" . | nindent 4 }}
{{- end }}
