apiVersion: v2
name: kuma
description: A Helm chart for the Kuma Control Plane
type: application
version: 1.8.0
appVersion: 1.8.0
home: https://github.com/kumahq/kuma
maintainers:
  - name: austince
    email: austin.cawley@gmail.com
  - name: jakubdyszkiewicz
    email: jakub.dyszkiewicz@konghq.com
  - name: nickolaev
    email: nikolay.nikolaev@konghq.com
icon: https://kuma.io/assets/images/brand/kuma-logo-new.svg
keywords:
  - service mesh
  - control plane
