components:
  schemas:
    PrometheusMetricsBackendConfig:
      properties:
        aggregate:
          items:
            properties:
              address:
                type: string
              enabled:
                type: boolean
              name:
                type: string
              path:
                type: string
              port:
                type: integer
            type: object
          type: array
        envoy:
          properties:
            filterRegex:
              type: string
            usedOnly:
              type: boolean
          type: object
        path:
          type: string
        port:
          type: integer
        skipMTLS:
          type: boolean
        tags:
          additionalProperties:
            type: string
          type: object
        tls:
          properties:
            mode:
              oneOf:
              - type: string
              - type: integer
          type: object
      type: object
info:
  x-ref-schema-name: PrometheusMetricsBackendConfig
openapi: 3.1.0
