{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zone-proxy
  labels:
    app: {{ .Release.Name }}-zone-proxy
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-zone-proxy
  ports:
    - name: proxy
      port: {{ .Values.service.port }}
      targetPort: proxy
{{- end }}
