---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: meshretries.kuma.io
spec:
  group: kuma.io
  names:
    categories:
    - kuma
    kind: MeshRetry
    listKind: MeshRetryList
    plural: meshretries
    singular: meshretry
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec is the specification of the Kuma MeshRetry resource.
            properties:
              targetRef:
                description: TargetRef is a reference to the resource the policy takes
                  an effect on. The resource could be either a real store object or
                  virtual resource defined inplace.
                properties:
                  kind:
                    description: Kind of the referenced resource
                    enum:
                    - Mesh
                    - MeshSubset
                    - MeshService
                    - MeshServiceSubset
                    - MeshGatewayRoute
                    type: string
                  mesh:
                    description: Mesh is reserved for future use to identify cross
                      mesh resources.
                    type: string
                  name:
                    description: 'Name of the referenced resource. Can only be used
                      with kinds: `MeshService`, `MeshServiceSubset` and `MeshGatewayRoute`'
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    description: Tags used to select a subset of proxies by tags.
                      Can only be used with kinds `MeshSubset` and `MeshServiceSubset`
                    type: object
                type: object
              to:
                description: To list makes a match between the consumed services and
                  corresponding configurations
                items:
                  properties:
                    default:
                      description: Default is a configuration specific to the group
                        of destinations referenced in 'targetRef'
                      properties:
                        grpc:
                          description: GRPC defines a configuration of retries for
                            GRPC traffic
                          properties:
                            backOff:
                              description: BackOff is a configuration of durations
                                which will be used in exponential backoff strategy
                                between retries
                              properties:
                                baseInterval:
                                  description: BaseInterval is an amount of time which
                                    should be taken between retries. Must be greater
                                    than zero. Values less than 1 ms are rounded up
                                    to 1 ms. Default is 25ms.
                                  type: string
                                maxInterval:
                                  description: MaxInterval is a maximal amount of
                                    time which will be taken between retries. Default
                                    is 10 times the "BaseInterval".
                                  type: string
                              type: object
                            numRetries:
                              description: NumRetries is the number of attempts that
                                will be made on failed (and retriable) requests
                              format: int32
                              type: integer
                            perTryTimeout:
                              description: PerTryTimeout is the amount of time after
                                which retry attempt should timeout. Setting this timeout
                                to 0 will disable it. Default is 15s.
                              type: string
                            retryOn:
                              description: 'RetryOn is a list of conditions which
                                will cause a retry. Available values are: [CANCELED,
                                DEADLINE_EXCEEDED, INTERNAL, RESOURCE_EXHAUSTED, UNAVAILABLE]'
                              items:
                                type: string
                              type: array
                          type: object
                        http:
                          description: HTTP defines a configuration of retries for
                            HTTP traffic
                          properties:
                            backOff:
                              description: BackOff is a configuration of durations
                                which will be used in exponential backoff strategy
                                between retries
                              properties:
                                baseInterval:
                                  description: BaseInterval is an amount of time which
                                    should be taken between retries. Must be greater
                                    than zero. Values less than 1 ms are rounded up
                                    to 1 ms. Default is 25ms.
                                  type: string
                                maxInterval:
                                  description: MaxInterval is a maximal amount of
                                    time which will be taken between retries. Default
                                    is 10 times the "BaseInterval".
                                  type: string
                              type: object
                            numRetries:
                              description: NumRetries is the number of attempts that
                                will be made on failed (and retriable) requests
                              format: int32
                              type: integer
                            perTryTimeout:
                              description: PerTryTimeout is the amount of time after
                                which retry attempt should timeout. Setting this timeout
                                to 0 will disable it. Default is 15s.
                              type: string
                            retriableRequestHeaders:
                              description: RetriableRequestHeaders is an HTTP headers
                                which must be present in the request for retries to
                                be attempted.
                              items:
                                properties:
                                  name:
                                    type: string
                                  type:
                                    enum:
                                    - REGULAR_EXPRESSION
                                    - EXACT
                                    - PREFIX
                                    type: string
                                  value:
                                    type: string
                                type: object
                              type: array
                            retriableResponseHeaders:
                              description: RetriableResponseHeaders is an HTTP response
                                headers that trigger a retry if present in the response.
                                A retry will be triggered if any of the header matches
                                match the upstream response headers.
                              items:
                                properties:
                                  name:
                                    type: string
                                  type:
                                    enum:
                                    - REGULAR_EXPRESSION
                                    - EXACT
                                    - PREFIX
                                    type: string
                                  value:
                                    type: string
                                type: object
                              type: array
                            retryOn:
                              description: 'RetryOn is a list of conditions which
                                will cause a retry. Available values are: [5XX, GATEWAY_ERROR,
                                RESET, RETRIABLE_4XX, CONNECT_FAILURE, ENVOY_RATELIMITED,
                                REFUSED_STREAM, HTTP3_POST_CONNECT_FAILURE, HTTP_METHOD_CONNECT,
                                HTTP_METHOD_DELETE, HTTP_METHOD_GET, HTTP_METHOD_HEAD,
                                HTTP_METHOD_OPTIONS, HTTP_METHOD_PATCH, HTTP_METHOD_POST,
                                HTTP_METHOD_PUT, HTTP_METHOD_TRACE]. Also, any HTTP
                                status code (500, 503, etc).'
                              items:
                                type: string
                              type: array
                          type: object
                        tcp:
                          description: TCP defines a configuration of retries for
                            TCP traffic
                          properties:
                            maxConnectAttempt:
                              description: MaxConnectAttempt is a maximal amount of
                                TCP connection attempts which will be made before
                                giving up
                              format: int32
                              type: integer
                          type: object
                      type: object
                    targetRef:
                      description: TargetRef is a reference to the resource that represents
                        a group of destinations.
                      properties:
                        kind:
                          description: Kind of the referenced resource
                          enum:
                          - Mesh
                          - MeshSubset
                          - MeshService
                          - MeshServiceSubset
                          - MeshGatewayRoute
                          type: string
                        mesh:
                          description: Mesh is reserved for future use to identify
                            cross mesh resources.
                          type: string
                        name:
                          description: 'Name of the referenced resource. Can only
                            be used with kinds: `MeshService`, `MeshServiceSubset`
                            and `MeshGatewayRoute`'
                          type: string
                        tags:
                          additionalProperties:
                            type: string
                          description: Tags used to select a subset of proxies by
                            tags. Can only be used with kinds `MeshSubset` and `MeshServiceSubset`
                          type: object
                      type: object
                  required:
                  - targetRef
                  type: object
                type: array
            required:
            - targetRef
            type: object
        type: object
    served: true
    storage: true
