name: "Build bom and licenses"
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 3 * * *
permissions: read-all
jobs:
  sbom:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: CycloneDX/gh-gomod-generate-sbom@efc74245d6802c8cefd925620515442756c70d8f # v2.0.0
        with:
          version: v1
          args: mod -licenses -json -output licenses.json
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: licenses
          path: |
            licenses.json
