apiVersion: v1
kind: Namespace
metadata:
  name: kuma-app
  kuma.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: kuma-tcp-echo
  namespace: kuma-app
spec:
  selector:
    app: kuma-tcp-echo
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-tcp-echo
  namespace: kuma-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuma-tcp-echo
  template:
    metadata:
      labels:
        app: kuma-tcp-echo
      annotations:
        kuma.io/mesh: default
    spec:
      containers:
      - name: kuma-tcp-echo
        image: kvn0218/kuma-tcp-echo
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
